### ISSUE TITLE
Add note about maintained versions

### ISSUE THREAD

**Issue by Nyholm** [SymfonyTest/SymfonyConfigTest#42]
We should have a note about the maintained versions. Maybe say that it is only the latest major versions that are maintained. 

Maybe create a table like https://github.com/guzzle/guzzle/blob/master/README.md ? It may contain last release, date and if it is maintained or not. 

@mwadon, is that something you could look into?

**Comment by mwadon** [comment]
Yes, sure. I will prepare it today. What do you think to put the latest version on the top in this table?

**Comment by Nyholm** [comment]
Excellent. 

I think that is a great idea.

**Comment by mwadon** [comment]
@Nyholm Do you think about something like this?
https://github.com/SymfonyTest/SymfonyConfigTest/pull/43

Should I add all 23 releases to this table?

**Comment by Nyholm** [comment]
Yeah, that looks good. 

No, not all 23. We only need the 3 major versions. The purpose is to show that version 1.x and 2.x is no longer maintained.

**Comment by mwadon** [comment]
Done

**Comment by Nyholm** [comment]
Great. Could you do the same on DependencyInjectionTest repo?

//Tobias Nyholm

Skickat på språng

**Comment by mwadon** [comment]
Done https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/91

**Comment by Nyholm** [comment]
Excellent.
