### ISSUE TITLE
Support for PHPUnit 7.0

### ISSUE THREAD

**Issue by Nyholm** [SymfonyTest/SymfonyConfigTest#46]
Should we do a new major release with PHPUnit7.0 support and dropping support for ~PHP7.1~ PHP7.0?

There is no way we can support PHPUnit6.0 and PHPUnit7.0 at the same time since they added return type annotation. 

Related to #44

**Comment by emodric** [comment]
> and dropping support for PHP7.1?

You meant 7.0, right? :)

**Comment by Nyholm** [comment]
Correct.

**Comment by Nyholm** [comment]
@fbourigault @mwadon @stloyd Can I get your input here?

**Comment by MarioBlazek** [comment]
@Nyholm currently I don't see any reasons why should we continue support PHP 7.0. For me it is ok to go with 7.1 as minimum. This should be analogous to PHPUnit requirements.

**Comment by MarioBlazek** [comment]
Any news here ?

**Comment by Nyholm** [comment]
Can we get your input here, @xabbuh?

**Comment by xabbuh** [comment]
Why not? :) Such a change would be a part of 3.2 anyway and if we notice serious issues in 3.1 we could still create patch releases for it.

**Comment by Nyholm** [comment]
Awesome. Thanks!

**Comment by rpkamp** [comment]
@Nyholm thanks for fixing this!

Could you also create a new tag release please?

**Comment by Nyholm** [comment]
Fixed, 4.0 is released.
