### ISSUE TITLE
Tag a new version for Symfony 5 compatibility

### ISSUE THREAD

**Issue by lolautruche** [SymfonyTest/SymfonyConfigTest#64]
Hello!

Could you please tag `4.0.2` (or maybe a minor version) so that we can have Symfony 5 support in a tag?

Thanks 😃 

#SymfonyHackday

**Comment by Nyholm** [comment]
Yes we should!

https://github.com/SymfonyTest/SymfonyConfigTest/pull/65

**Comment by Nyholm** [comment]
https://github.com/SymfonyTest/SymfonyConfigTest/releases/tag/4.1.0

**Comment by lolautruche** [comment]
Thanks
