### ISSUE TITLE
RFC | New major release - 5.0

### ISSUE THREAD

**Issue by stloyd** [SymfonyTest/SymfonyConfigTest#70]
Hey folks!

I would like to start taking the requirements & wishes for new major release.

Todo list:
- [x] Drop support for PHP <7.4,
- [x] Drop support for PHPUnit: <9.5,
- [x] Add support for PHP 8.1

Cheers!

**Comment by rpkamp** [comment]
While you're at it, might as well add support for PHP 8.2 too :slightly_smiling_face:

**Comment by matthiasnoback** [comment]
Feel free to make a PR for that, I'm watching this repo for changes now
hehe.
